### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by humanagent** [koisose/frame#1]
Hello there! I wanted to thank you for your contribution to OpenFrame. I am happy to let you know that your work has been added to the [Awesome-Open-Frame](https://github.com/open-frames/awesome-open-frames) repository. It would be great if you could update your readme with a brief description of the frame along with an image showcasing it. Adding the URL in the repository description and readme would make it easier for users to try it out. Thank you!

README
- Title
- Description
- Image or Gif in Converse or Warpcast
- Live URL

Also, here is a cool example i found from the submissions: https://github.com/rtomas/peace-frame-farcaster

**Comment by uratmangun** [comment]
@fabriguespe thanks for accepting my repo but i actually already put live demo and youtube url in the readme is this still not enough? 
![image](https://github.com/koisose/frame/assets/17805677/dc619cb0-f4ee-4c8b-8664-f6de52dc2f16)

**Comment by humanagent** [comment]
Would be cool to have images :)
 Specially in-chat images

**Comment by uratmangun** [comment]
@fabriguespe like this ? 
![image](https://github.com/koisose/frame/assets/17805677/06e1c4ec-af97-4def-ac07-56a37114138c)
